### ISSUE TITLE
no_alloc not supported

### ISSUE THREAD

**Issue by ayushagrawal2** [atlas-aero/rt-PCA9539#2]
I've been trying to use this library in a `no_std` environment, but I'm running into a compile time `no global memory allocator error` with `test` disabled. This appears to be due to the use of `alloc::borrow::ToOwned`. Do I need to configure something else in my environment? 

I'm opening a PR with a small patch that I've been using for the past month -- feel free to ignore if it is indeed a configuration issue.

**Comment by marius-meissner** [comment]
Many thanks for the issue and the PR. It looks very promising!
Just for the sake of correctness: no_std != no_alloc.

**Comment by ayushagrawal2** [comment]
Thanks!
